const SET_ACCOUNT = "SET_ACCOUNT";
const SET_ACCOUNT_DATA = "SET_ACCOUNT_DATA";
const SET_ACCOUNT_TYPE = "SET_ACCOUNT_TYPE";
const CLEAN_ACCOUNT = "CLEAN_ACCOUNT";
const CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT";

export { SET_ACCOUNT, SET_ACCOUNT_DATA, SET_ACCOUNT_TYPE, CLEAN_ACCOUNT, CREATE_USER_ACCOUNT };